name: Executar testes unitarios

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout other repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/bluesburger/ordering-system.git  # Substitua pela URL do seu repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test