name: Create Terraform Plan for infra

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_rdsUser: ${{ secrets.AWS_RDS_USER }}
  TF_VAR_rdsPass: ${{ secrets.AWS_RDS_PASS }}

permissions:
  pull-requests: write

jobs:
  plan-prod:
    name: 'Terraform infra'
    runs-on: ubuntu-latest
    environment: 'marlondev'
    env:
      TF_WORKING_DIR: '.'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: TF_LOG=DEBUG terraform plan -input=false -no-color -out latest
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve